# Generated by Django 4.0.1 on 2022-04-04 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fic',
            fields=[
                ('workid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1250)),
            ],
        ),
        migrations.CreateModel(
            name='FicAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fic')),
            ],
        ),
        migrations.AddField(
            model_name='fic',
            name='authors',
            field=models.ManyToManyField(through='api.FicAuthor', to='api.Author'),
        ),
        migrations.CreateModel(
            name='CatalogueFic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.catalogue')),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fic')),
            ],
        ),
        migrations.AddField(
            model_name='catalogue',
            name='fics',
            field=models.ManyToManyField(through='api.CatalogueFic', to='api.Fic'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ficauthor',
            constraint=models.UniqueConstraint(fields=('fic', 'author'), name='fic_author_unique'),
        ),
        migrations.AddConstraint(
            model_name='cataloguefic',
            constraint=models.UniqueConstraint(fields=('catalogue', 'fic'), name='fic_unique_in_catalog'),
        ),
        migrations.AddConstraint(
            model_name='catalogue',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='catalogue_title_unique'),
        ),
    ]
