# Generated by Django 4.0.1 on 2022-03-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_userid_catalog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguefic',
            name='workid',
            field=models.IntegerField(default=0),
        ),
    ]
