# Generated by Django 4.0.1 on 2022-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cataloguefic_workid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cataloguefic',
            constraint=models.UniqueConstraint(fields=('catalogue', 'workid'), name='fic_unique_in_catalogue'),
        ),
    ]
