# Generated by Django 4.0.1 on 2022-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cataloguefic_fic_unique_in_catalogue'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cataloguefic',
            name='fic_unique_in_catalogue',
        ),
        migrations.RenameField(
            model_name='cataloguefic',
            old_name='catalogue',
            new_name='catalog',
        ),
        migrations.AddConstraint(
            model_name='cataloguefic',
            constraint=models.UniqueConstraint(fields=('catalog', 'workid'), name='fic_unique_in_catalog'),
        ),
    ]
