# Generated by Django 4.0.1 on 2022-03-13 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_cataloguefic_fic_unique_in_catalogue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Catalogue',
        ),
        migrations.RemoveConstraint(
            model_name='cataloguefic',
            name='fic_unique_in_catalog',
        ),
        migrations.RenameField(
            model_name='cataloguefic',
            old_name='catalog',
            new_name='catalogue',
        ),
        migrations.AddConstraint(
            model_name='catalogue',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='catalogue_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='cataloguefic',
            constraint=models.UniqueConstraint(fields=('catalogue', 'workid'), name='fic_unique_in_catalog'),
        ),
    ]
