# Generated by Django 4.0.1 on 2022-04-04 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_ficauthors_ficauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cataloguefic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
